platform:
- x86
- x64

install:
- ps: |
    # This is necessary because AppVeyor uses 64 bit environemnt even if "platform: x86" is specified.
    # see also <http://help.appveyor.com/discussions/questions/213-platform-x86-is-not-32-bit>
    if ("x86".Equals(${env:PLATFORM})) {
      $env:ChocoOptions = "--x86"
      $env:HPPath = "${env:ProgramFiles(x86)}\Haskell Platform\2014.2.0.0"
    } else {
      $env:ChocoOptions = ""
      $env:HPPath = "${env:ProgramFiles}\Haskell Platform\2014.2.0.0"
    }
    choco install ${env:ChocoOptions} haskellplatform -version 2014.2.0.0 -y
    # Haskell Platfrom package doesn't update PATH for the current shell instance
    $env:Path += ";${env:HPPath}\bin"
    $env:Path += ";${env:HPPath}\lib\extralibs\bin"
    $env:Path += ";${env:HPPath}\mingw\bin"
    $env:Path += ";.\.cabal-sandbox\bin"
    choco install ${env:ChocoOptions} wixtoolset -version 3.10.1.2213 -y
    $env:Path += ";${env:ProgramFiles}\WiX Toolset v3.10\bin"
    $env:Path += ";${env:ProgramFiles(x86)}\WiX Toolset v3.10\bin"
- cabal sandbox init
- cabal update
- cabal install --only-dependencies --enable-tests --enable-benchmarks -fHaskeline -f-Readline

build_script:
- cabal configure --enable-tests --enable-benchmarks -fHaskeline -f-Readline -v2 # -v2 provides useful information for debugging
- cabal build

after_build:
- cmd: |
   cd windows
   echo Creating msi...
   runhaskell build_msi.hs
   cd ..

test_script:
- cabal test
- cabal check
- cabal sdist

artifacts:
- path: windows\*.msi
  name: Windows Installer
